language: java
os: 
  - linux
jdk: 
  - openjdk11
cache:
  directories:
   - $HOME/.m2

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
   
install:
  - pip install -r requirements.txt

script: mvn clean verify -f pybridge
