language: java
os: 
  - linux
jdk: 
  - openjdk11
cache:
  directories:
   - $HOME/.m2

addons:
  apt: 
    sources: 
      - deadsnakes
    packages:
      - python3.4
   
install:
  - pip install -r requirements.txt

script: python pybridgeApplication.py
