matrix:
  include:
    -language: java
      os: linux
      jdk: openjdk11
    cache:
      directories:
       - $HOME/.m2
       
     -language: python
      python: 3.7
   
install:
  - pip install -r requirements.txt

script: mvn clean verify -f pybridge
